# Generated by Django 4.2.4 on 2023-11-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_practicante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechaInicio', models.CharField(max_length=50)),
                ('fechaTermino', models.CharField(max_length=50)),
                ('sbp', models.IntegerField()),
                ('dbp', models.IntegerField()),
                ('pulso', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('saturacion', models.IntegerField()),
                ('paciente', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
    ]
